SELECT SAL FROM EMP WHERE ENAME = 'JONES';
SELECT * FROM EMP WHERE SAL > 2975;
SELECT ENAME, SAL FROM EMP WHERE SAL > ( SELECT SAL FROM EMP
WHERE ENAME = 'JONES');
SELECT *
  FROM EMP
  WHERE SAL > ( SELECT SAL
                  FROM EMP
                 WHERE ENAME = 'JONES'); -- 서브쿼리로 JONES의 급여보다 높은 급여를 받는 사원정보 출력하기

SELECT * FROM EMP WHERE COMM > ( SELECT COMM FROM EMP
WHERE ENAME = 'ALLEN'); -- 단일행 서브쿼리

SELECT * FROM EMP WHERE HIREDATE < ( SELECT HIREDATE
FROM EMP WHERE ENAME = 'SCOTT'); -- 서브쿼리의 결과 값이 날짜형인 경우

SELECT E.EMPNO, E.ENAME, E.JOB, E.SAL, D.DEPTNO, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND E.DEPTNO = 20 AND E.SAL> ( SELECT AVG(SAL) FROM EMP); -- 서브쿼리 안에서 함수를 사용한 경우

SELECT E.EMPNO, E.ENAME, E.JOB, E.SAL, D.DEPTNO, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO 
AND E.DEPTNO = 20
AND E.SAL<=( SELECT AVG(SAL) FROM EMP);

SELECT * FROM EMP WHERE DEPTNO IN (20,30);
SELECT * FROM EMP WHERE SAL IN (SELECT MAX(SAL)
FROM EMP GROUP BY DEPTNO);

SELECT * FROM EMP 
WHERE SAL = ANY(SELECT MAX(SAL)
FROM EMP GROUP BY DEPTNO);

SELECT * FROM EMP
WHERE SAL = SOME (SELECT MAX(SAL)
FROM EMP GROUP BY DEPTNO);

SELECT * FROM EMP
WHERE SAL < ANY (SELECT SAL FROM EMP WHERE DEPTNO =30)
ORDER BY SAL, EMPNO;

SELECT * FROM EMP WHERE DEPTNO = 30;

SELECT * FROM EMP
WHERE SAL < ANY (SELECT SAL FROM EMP WHERE DEPTNO = 30)
ORDER BY SAL ,EMPNO;

SELECT *
FROM EMP
WHERE SAL < ALL (SELECT SAL
FROM EMP WHERE DEPTNO = 30);

SELECT * FROM EMP
WHERE EXISTS ( SELECT DNAME FROM DEPT WHERE DEPTNO = 50);

SELECT * FROM EMP
WHERE HIREDATE< ALL(SELECT ALL HIREDATE FROM EMP WHERE DEPTNO = 10);

SELECT E10.EMPNO, E10.ENAME, E10.DEPTNO, D.DNAME, D.LOC
FROM (SELECT * FROM EMP WHERE DEPTNO = 10) E10
,(SELECT * FROM DEPT) D
WHERE E10.DEPTNO = D.DEPTNO;

WITH
E10 AS (SELECT * FROM EMP WHERE DEPTNO = 10)
,D AS(SELECT * FROM DEPT)
SELECT E10.EMPNO, E10.ENAME, E10.DEPTNO, D.DNAME, D.LOC
FROM E10, D
WHERE E10.DEPTNO = D.DEPTNO;

SELECT EMPNO, ENAME, JOB, SAL
,( SELECT GRADE FROM SALGRADE
WHERE E.SAL BETWEEN LOSAL AND HISAL) AS SALGRADE, DEPTNO
, ( SELECT DNAME FROM DEPT WHERE E.DEPTNO = DEPT.DEPTNO) AS DNAME
FROM EMP E;

CREATE TABLE DEPT_TEMP
AS SELECT * FROM DEPT;

CREATE TABLE EMP_TEMP10 AS SELECT * FROM EMP;
SELECT * FROM EMP_TEMP10;

INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
VALUES(50, 'DATABASE', 'SEOUL');
SELECT * FROM DEPT_TEMP;

INSERT INTO DEPT_TEMP(DEPTNO, DNAME,LOC)
VALUES(60, 'NETWORK');

INSERT INTO DEPT_TEMP
VALUES(60,'NETWORK','BUSAN');
SELECT * FROM DEPT_TEMP;

INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
VALUES (70,'WEB',NULL);
SELECT * FROM DEPT_TEMP;
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
VALUES (80,'MOBIE','');
SELECT * FROM DEPT_TEMP;
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
VALUES (90,'SPACE',' ');

INSERT INTO DEPT_TEMP(DEPTNO, LOC)
VALUES(90, 'INCHEON');
SELECT * FROM DEPT_TEMP;

CREATE TABLE EMP_TEMP
AS SELECT * FROM EMP WHERE 1<>1;

SELECT * FROM EMP_TEMP;

INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES(0926, '김주형', 'PRESIDENT', NULL,ADD_MONTHS(SYSDATE,120)
,5000,1000,10);
SELECT * FROM EMP_TEMP;
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES(1111,'성춘향','MANAGER', 9999,'2001-01-05',4000,NULL,20);
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES(1111,'이순신','MANAGER', 9999,'07/01/2001',4000,NULL,20);
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES(1111,'이몽룡','MANAGER', 9999,'07-01-2001',4000,NULL,20);

INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR
,HIREDATE, SAL, COMM, DEPTNO)
VALUES (2111, '이순신', 'MANAGER',9999
, TO_DATE('07/01/2001', 'DD/MM/YYYY')
,4000,NULL,20);

INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR
,HIREDATE, SAL, COMM, DEPTNO)
VALUES (3111, '심청이', 'MANAGER',9999
, SYSDATE,4000,NULL,20);

SELECT * FROM EMP_TEMP;

INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM,DEPTNO)
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE,E.SAL, E.COMM, E.DEPTNO
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
AND S.GRADE =1;

SELECT * FROM EMP_TEMP;





